### PR TITLE
Linked list v1

### PR DESCRIPTION
**Pull request by animeshk874**

### CODE REVIEW

**Comment by animeshk874** [comment]
@vikaskumr @surya76657 URL -> https://606029fc0c68e100076da871--ds-in-js.netlify.app

**Comment by surya76657** [comment]
> @vikaskumr @surya76657 URL -> https://606029fc0c68e100076da871--ds-in-js.netlify.app

@animeshk874 actually some css is broken on mobile

**Comment by animeshk874** [comment]
> > @vikaskumr @surya76657 URL -> https://606029fc0c68e100076da871--ds-in-js.netlify.app
> 
> @animeshk874 actually some css is broken on mobile

Yes. Creating an issue for it. Will have to fix it
https://github.com/animeshk874/data-structures-in-js/issues/23

**Review by surya76657 — APPROVED** [review]

**Comment by surya76657** [comment]
one conflicts is there please resolve this

**Pull request merged**
